version: "3.7"
services:
  teamcity-server:
    image: vlrpi/teamcity-server:ubuntu-xenial-2021.1
    container_name: server
    networks:
      - teamcity-net
    ports:
      - 8111:8111
    environment:
      TEAMCITY_DATA_PATH: /TeamCity/data
      TEAMCITY_LOGS_PATH: /TeamCity/logs
    volumes:
      - ./data:/TeamCity/data
      - ./logs:/TeamCity/logs

  teamcity-agent:
    image: vlrpi/teamcity-agent-arm64v8:ubuntu-xenial-2021.1
    container_name: agent
    networks:
      - teamcity-net
    environment:
      SERVER_URL: http://server:8111
    volumes:
      - ./agent:/Teamcity/conf

networks:
  teamcity-net:
    driver: bridge
